### ISSUE TITLE
Choose branch based on rebuilds

### ISSUE THREAD

**Issue by FRidh** [ryantm/nix-update#2]
I like what you wrote here for updating packages, although it does create a lot of work for the people that need to merge it. 

One improvement I would like to see is if you would check before opening such a PR how much needs to be rebuild, and based on that choose a branch. @GrahamcOfBorg does already a bit of this so you might want to coordinate with @grahamc how to solve this. Maybe @GrahamcOfBorg can be improved to modify the branch, in which case there is no need to make a change here.

**Comment by ryantm** [comment]
If the GitHub interface provided an easy way to cherry pick a commit on top of a different branch, this wouldn't really be a problem. I was planning to make a script to cherry pick the commits quickly, but I haven't done that yet.

**Comment by ryantm** [comment]
I made a script that lets me move to staging quickly, so I've done that on all the packages on my latest run. But I want to do the package change eval that OfBorg does so I know which branch to commit and build on top of in the first place. I know how to do it, it's just a matter of adding it in. It will unfortunately make things a lot slower, but it's probably worth it.

**Comment by FRidh** [comment]
Changing branch after a PR is a bit unfortunate due to a "bug" in GitHub which then typically notifies all code maintainers.

**Comment by ryantm** [comment]
I think using the `git merge-base` for the base of the commit (as I have been doing for a week now) works well enough to not bother trying to figure out ahead of time which branch to send it to, because you can change the PR from master to staging without pinging anyone or making a big commit history appear on the GitHub UI. So I'm closing for now, but feel free to push for something better if you disagree!
