### ISSUE TITLE
Don’t auto-update golang (npm, rust, …) packages

### ISSUE THREAD

**Issue by Profpatsch** [ryantm/nix-update#6]
golang and npm use the concept of lockfiles, carrying all their files with them. Just changing the version string doesn’t cut it in these cases, the dependencies have to be updated as well (if the lockfile changes), for example https://github.com/NixOS/nixpkgs/commit/413e41db9da54ea1ce4e1552e7815e0342dbe16e#diff-78d6ebbd9a005053af6388888c66decf (in this case the lockfile luckily didn’t change).

The languages I know of that use lockfiles are:
* node (`yarn.lock` for yarn and `package-lock.json` for npm)
* rust (`cargo.lock`)
* golang (sometimes master, sometimes `vendor.conf` sometimes something different)

It could be automated, but requires some work. Until then I suggest we are conservative.

**Comment by ryantm** [comment]
@Profpatsch Thanks for raising this issue, and I agree they should be excluded until then. Someone already asked to exclude all the python packages because of the python 2 vs 3 issue. 

Where is the lockfile for the buildah package and how does the builder refer to it? I was expecting to find it in the nixpkgs repository next to the default.nix file.

**Comment by Profpatsch** [comment]
Okay, my bad. In case of `buildah`, they use a `vendor/` directory which contains all the sources of all dependencies (ikr). So that would be a rule for `golang`, if there is a `vendor/` dir you can update.
